# Generated by Django 3.1.5 on 2021-01-15 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0015_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
