# Generated by Django 3.1.5 on 2021-01-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_auto_20210104_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
