# Generated by Django 3.1.5 on 2021-01-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_auto_20210110_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='click the link to read the full post...', max_length=255),
        ),
    ]
